openapi: 3.0.0

info:
  title: monitorias
  version: 0.0.0

paths:
  /monitorias:
    get:
      responses:
        "200":
          description: "lista de todas as monitorias"
          content:
            application/json: {}


  /monitoria/{id}:
    get:

  /monitores:
    get:

  /monitor/{id}:
    get:

  /disciplinas:
    get:

  /disciplina/{id}:
    get:

  /alunos:
    get:

  /aluno/{id}:
    get:
